name: validate
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/
      - name: Setup Jobs
        id: setup-jobs
        shell: bash
        run: ./.github/workflows/scripts/setup-matrix.sh
    outputs:
      matrix: ${{ steps.setup-jobs.outputs.matrix }}
  unity-build:
    if: needs.setup.outputs.matrix
    needs: setup
    name: Validate
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
      fail-fast: false
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      matrix: ${{ toJSON(matrix.matrix) }}